### ISSUE TITLE
Home menu always red?

### ISSUE THREAD

**Issue by axel-rank** [tranduyhung/grav-theme-mache#1]
Hi, very nice theme.
The Home menu stays always red even if I click on another menu . Shouldn't only the active menu icon have a red color? 
Using Firefox 57.0.3

![foto](https://user-images.githubusercontent.com/12480617/34446615-cf9448fa-ecdc-11e7-98a7-9fdd90b79015.png)

**Comment by tranduyhung** [comment]
It was a link to the homepage itself, not an anchor to the top of the page, that's why it was red. This is fixed in 1.0.3 version.
