### ISSUE TITLE
Form contact in multiple page

### ISSUE THREAD

**Issue by unmick** [tranduyhung/grav-theme-mache#3]
Hello,

As i would like to use the form in a single page, i have duplicated the form.html.twig from antimaster.
I have tried to adjust it but it's ugly : no label displayed and so on.
![image](https://user-images.githubusercontent.com/35163557/34898762-fbe1b41a-f7f4-11e7-88f9-5a9d0cc1e756.png)

If you have any advice or way of search ....

Thank you

form.html.twig : 
{% extends 'partials/base.html.twig' %}

{% block content %}
{% set image = '' %}
{% if theme_config.default_background_image|length > 0 %}
    {% for item in theme_config.default_background_image %}
        {% set image = item.name %}
    {% endfor %}
{% endif %}

<div class="banner banner-alt"{% if image %} style="background-image: url({{ url('theme://images/' ~ image) }})"{% endif %}>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ page.title }}</h1>
                <span class="line"></span>
                <div class="top">{{ page.header.summary }}</div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row content">
        {{ page.content }}
    </div>
</div>
    {% include "forms/form.html.twig" %}

{% endblock %}

**Comment by tranduyhung** [comment]
Antimatter doesn't have styles for form and it uses a different CSS framework, while Mache uses Bootstrap.

You need to add some Bootstrap's CSS styles to your form fields (```outerclasses``` attribute), an example is here: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-mache/master/pages/01.home/modular.md

**Comment by unmick** [comment]
I have tried to add the modular.md but when i add it, i lost my header and overall my menu.
My first menu is overwritten .
![image](https://user-images.githubusercontent.com/35163557/34906247-db9f71d6-f869-11e7-8249-009587364f8b.png)

Main menu : 
![image](https://user-images.githubusercontent.com/35163557/34906255-0adafe5c-f86a-11e7-99e3-0b3781ac1422.png)

after  the mache page clicked : 
![image](https://user-images.githubusercontent.com/35163557/34906262-2e3426e4-f86a-11e7-98d6-c26797164251.png)

Thanks
